### ISSUE TITLE
安卓报错，请解决

### ISSUE THREAD

**Issue by xdongliu123** [libpag/pag-flutter#17]
W/_plugin_exampl(27316): Accessing hidden method Landroid/app/ActivityThread;->currentApplication()Landroid/app/Application; (greylist, reflection, allowed)
I/LibraryLoadUtils(27316): loadLibrary pag fail! Error: dlopen failed: library "libpag.so" not found
I/LibraryLoadUtils(27316): load  fail! Error: dlopen failed: library "/data/user/0/com.example.flutter_pag_plugin_example/lib/libpag.so" not found
E/_plugin_exampl(27316): No implementation found for void org.libpag.PAGLayer.nativeInit() (tried Java_org_libpag_PAGLayer_nativeInit and Java_org_libpag_PAGLayer_nativeInit__)
E/AndroidRuntime(27316): FATAL EXCEPTION: main
E/AndroidRuntime(27316): Process: com.example.flutter_pag_plugin_example, PID: 27316
E/AndroidRuntime(27316): java.lang.UnsatisfiedLinkError: No implementation found for void org.libpag.PAGLayer.nativeInit() (tried Java_org_libpag_PAGLayer_nativeInit and Java_org_libpag_PAGLayer_nativeInit__)
E/AndroidRuntime(27316): 	at org.libpag.PAGLayer.nativeInit(Native Method)
E/AndroidRuntime(27316): 	at org.libpag.PAGLayer.<clinit>(PAGLayer.java:211)
E/AndroidRuntime(27316): 	at org.libpag.PAGFile.Load(PAGFile.java:35)
E/AndroidRuntime(27316): 	at com.example.flutter_pag_plugin.FlutterPagPlugin.initPag(FlutterPagPlugin.java:186)
E/AndroidRuntime(27316): 	at com.example.flutter_pag_plugin.FlutterPagPlugin.onMethodCall(FlutterPagPlugin.java:125)
E/AndroidRuntime(27316): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)

**Comment by skylerpfli** [comment]
java.lang.UnsatisfiedLinkError 的报错，原因是架构匹配的问题，pag 提供了三个架构：arm64-v8a、armeabi、armeabi-v7a，检查下你们的项目是否对应进行了匹配，关注下报错机型的架构

模拟器可能无法使用
