### ISSUE TITLE
能否新增 resume 方法, 和 pause 对称使用?

### ISSUE THREAD

**Issue by zzz2016** [libpag/pag-flutter#24]
RT.
pause 后无法恢复原状态.

**Comment by gdoujk1123ljm** [comment]
调用start不行吗？

**Comment by skylerpfli** [comment]
直接调用pagKey.currentState?.start();就可以了

**Comment by zzz2016** [comment]
> 直接调用pagKey.currentState?.start();就可以了

直接调用 start 会将动画进程从0 开始.
resume 应该可以从 pause 的动画进程恢复.

**Comment by gdoujk1123ljm** [comment]
双端已统一，使用start可以继续播放
