### ISSUE TITLE
安卓机型运行后，循环播放会不停运行打印日志，这个太频繁了，能否去掉

### ISSUE THREAD

**Issue by lixiaoblack** [libpag/pag-flutter#25]

**Comment by lixiaoblack** [comment]
<img width="835" alt="image" src="https://user-images.githubusercontent.com/49580089/236136762-fdbb075c-886d-42d2-b32e-13d22a407c45.png">

**Comment by skylerpfli** [comment]
已支持从Flutter资源路径中加载，如果是手机本地存储的路径。可以先在外部加载好后，用PAGView.bytes传入二进制。
