### ISSUE TITLE
macos下，无法在模拟器中播放

### ISSUE THREAD

**Issue by motionz-von** [libpag/pag-flutter#28]
# 重现步骤
1. m2芯片的mac os 13.3.1上，使用iPhone12 mini模拟器
2. clone master分支
3. 运行example, 所有pag动画的位置都是白屏
4. 看日志，onInit/onAnimationRepeat等都有调用。debug console无报错
5. flutter版本v3.7.12

**Comment by gdoujk1123ljm** [comment]
模拟器暂时未支持
