### ISSUE TITLE
kotlin-gradle-plugin版本太低了，会考虑升级吗？

### ISSUE THREAD

**Issue by WanXuJiao** [libpag/pag-flutter#29]
FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':pag' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.20

**Comment by llqidian** [comment]
是的 我也遇到了 能调整下吗

**Comment by WanXuJiao** [comment]
您的来信已收到,谢谢!
如有疑问,我会尽快给您回复.
祝您工作愉快!
                                        总经理办秘书科 小焦
                                        0352 7868327

**Comment by skylerpfli** [comment]
已经调整过了1.0.3版本

**Comment by Cedar-byte** [comment]
1.0.4版本还是会报同样的错误
`* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':pag' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.20`

**Comment by WanXuJiao** [comment]
您的来信已收到,谢谢!
如有疑问,我会尽快给您回复.
祝您工作愉快!
                                        总经理办秘书科 小焦
                                        0352 7868327
