### ISSUE TITLE
Error (Xcode): Undefined symbol: std::__1::chrono::steady_clock::now()

### ISSUE THREAD

**Issue by ali-raza-flutter** [libpag/pag-flutter#3]
I am facing following error on IOS only everything is working fine on android

`Launching lib/main.dart on Ali Raza’s iPhone in debug mode...
lib/main.dart:1
Automatically signing iOS for device deployment using specified development team in Xcode project: UVDDXWFW8V
Xcode build done.                                           17.2s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    Writing result bundle at path:
    	/var/folders/vm/153bqtbn5cvcpwrb76hpqnw80000gp/T/flutter_tools.BOQC44/flutter_ios_build_temp_dirJpjCOV/temporary_xcresult_bundle
    Undefined symbols for architecture arm64:
      "std::__1::chrono::steady_clock::now()", referenced from:
          GetCurrentTimeUS() in flutter_pag_plugin(TGFlutterPagRender.o)
      "___cxa_guard_acquire", referenced from:
          GetCurrentTimeUS() in flutter_pag_plugin(TGFlutterPagRender.o)
      "___cxa_guard_release", referenced from:
          GetCurrentTimeUS() in flutter_pag_plugin(TGFlutterPagRender.o)
      "___gxx_personality_v0", referenced from:
          -[TGFlutterPagRender initWithPagData:progress:autoPlay:frameUpdateCallback:] in flutter_pag_plugin(TGFlutterPagRender.o)
          -[TGFlutterPagRender startRender] in flutter_pag_plugin(TGFlutterPagRender.o)
          -[TGFlutterPagRender getLayersUnderPoint:] in flutter_pag_plugin(TGFlutterPagRender.o)
    ld: symbol(s) not found for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Building targets in dependency order
    warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Runner' from project 'Runner')
    warning: Run script build phase 'Thin Binary' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Runner' from project 'Runner')
    /Users/aliraza/Projects/video_player_example/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 11.0 to 16.0.99. (in target 'libpag' from project 'Pods')
    Result bundle written to path:
    	/var/folders/vm/153bqtbn5cvcpwrb76hpqnw80000gp/T/flutter_tools.BOQC44/flutter_ios_build_temp_dirJpjCOV/temporary_xcresult_bundle
Could not build the precompiled application for the device.
Error (Xcode): Undefined symbol: std::__1::chrono::steady_clock::now()

Error (Xcode): Undefined symbol: ___cxa_guard_acquire

Error (Xcode): Undefined symbol: ___cxa_guard_release

Error (Xcode): Undefined symbol: ___gxx_personality_v0

Error launching application on Ali Raza’s iPhone.
Exited`

I am running it on I phone XS runing IOS 16.0

here is my flutter doctor output

`octor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.6 21G115 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.72.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability`

**Comment by lzou** [comment]
> 

请问解决了吗？我也遇到了一样的问题

**Comment by lzou** [comment]
> I am facing following error on IOS only everything is working fine on android
> 
> `Launching lib/main.dart on Ali Raza’s iPhone in debug mode... lib/main.dart:1 Automatically signing iOS for device deployment using specified development team in Xcode project: UVDDXWFW8V Xcode build done. 17.2s Failed to build iOS app Error output from Xcode build: ↳ ** BUILD FAILED ** Xcode's output: ↳ Writing result bundle at path: /var/folders/vm/153bqtbn5cvcpwrb76hpqnw80000gp/T/flutter_tools.BOQC44/flutter_ios_build_temp_dirJpjCOV/temporary_xcresult_bundle Undefined symbols for architecture arm64: "std::__1::chrono::steady_clock::now()", referenced from: GetCurrentTimeUS() in flutter_pag_plugin(TGFlutterPagRender.o) "___cxa_guard_acquire", referenced from: GetCurrentTimeUS() in flutter_pag_plugin(TGFlutterPagRender.o) "___cxa_guard_release", referenced from: GetCurrentTimeUS() in flutter_pag_plugin(TGFlutterPagRender.o) "___gxx_personality_v0", referenced from: -[TGFlutterPagRender initWithPagData:progress:autoPlay:frameUpdateCallback:] in flutter_pag_plugin(TGFlutterPagRender.o) -[TGFlutterPagRender startRender] in flutter_pag_plugin(TGFlutterPagRender.o) -[TGFlutterPagRender getLayersUnderPoint:] in flutter_pag_plugin(TGFlutterPagRender.o) ld: symbol(s) not found for architecture arm64 clang: error: linker command failed with exit code 1 (use -v to see invocation) note: Building targets in dependency order warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Runner' from project 'Runner') warning: Run script build phase 'Thin Binary' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Runner' from project 'Runner') /Users/aliraza/Projects/video_player_example/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 11.0 to 16.0.99. (in target 'libpag' from project 'Pods') Result bundle written to path: /var/folders/vm/153bqtbn5cvcpwrb76hpqnw80000gp/T/flutter_tools.BOQC44/flutter_ios_build_temp_dirJpjCOV/temporary_xcresult_bundle Could not build the precompiled application for the device. Error (Xcode): Undefined symbol: std::__1::chrono::steady_clock::now()
> 
> Error (Xcode): Undefined symbol: ___cxa_guard_acquire
> 
> Error (Xcode): Undefined symbol: ___cxa_guard_release
> 
> Error (Xcode): Undefined symbol: ___gxx_personality_v0
> 
> Error launching application on Ali Raza’s iPhone. Exited`
> 
> I am running it on I phone XS runing IOS 16.0
> 
> here is my flutter doctor output
> 
> `octor summary (to see all details, run flutter doctor -v): [✓] Flutter (Channel stable, 3.3.4, on macOS 12.6 21G115 darwin-x64, locale en-GB) [✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc2) [✓] Xcode - develop for iOS and macOS (Xcode 14.0.1) [✓] Chrome - develop for the web [✓] Android Studio (version 2021.3) [✓] VS Code (version 1.72.0) [✓] Connected device (3 available) [✓] HTTP Host Availability`

i have the same question. have you slove it?
