### ISSUE TITLE
Flutter打release包闪退，这是什么造成的？

### ISSUE THREAD

**Issue by Wendale** [libpag/pag-flutter#33]
flutter debug的时候没问题，打release包安装，遇到pag就闪退，这是怎么回事？

**Comment by Wendale** [comment]
-keep class org.libpag.**{*;}

**Comment by FaDrYL** [comment]
我也遇到了，“androidx.exifinterface.media.ExifInterface” 这个类被 shrink 掉了，所以 JNI 找不到。
需要加上
`-keep class androidx.exifinterface.**{*;}`
