### ISSUE TITLE
运行是提示The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher

### ISSUE THREAD

**Issue by Camwly** [libpag/pag-flutter#36]
The following dependencies do not satisfy the required version:
project ':pag' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.20

**Comment by applebest** [comment]
https://github.com/libpag/pag-flutter/issues/49

**Comment by jimmyfly100** [comment]
1.0.7已支持
