### ISSUE TITLE
kotlin-gradle-plugin版本不兼容

### ISSUE THREAD

**Issue by Cedar-byte** [libpag/pag-flutter#44]
依赖版本号1.0.4，运行报错：
`
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':pag' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.20
`

**Comment by ChengYu08** [comment]
改为 org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.20  依旧有问题 
感觉是flutter 版本问题 我看插件内还是
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"
  
  我们项目都是
environment:
  sdk: '>=3.2.0 <4.0.0'

**Comment by Fifapig** [comment]
有什么解决方案吗？

**Comment by shejishi** [comment]
遇到同样的问题，有解决方案吗？

**Comment by jimmyfly100** [comment]
1.0.7版本已升级kotlin版本依赖
