### ISSUE TITLE
PAGView.asset报错：PAGViewState error: PlatformException(-1100, load composition is null! , null, null)

### ISSUE THREAD

**Issue by lsfern** [libpag/pag-flutter#46]
PAGView.asset报错：PAGViewState error: PlatformException(-1100, load composition is null! , null, null)

![image](https://github.com/libpag/pag-flutter/assets/32630118/64272b41-b69b-4568-9f0f-d46a8f17bcf8)

但是在线预览是没问题的，这个错误码具体是啥原因呢

**Comment by skylerpfli** [comment]
加载资源文件失败，可以看下资源路径有没有问题哈
