### ISSUE TITLE
project ':pag' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.20  ， 这个库维护的人都被裁了吗？

### ISSUE THREAD

**Issue by applebest** [libpag/pag-flutter#49]
<img width="1612" alt="image" src="https://github.com/libpag/pag-flutter/assets/16376401/0011cae3-8296-47c8-bd1b-114084968b7e">
版本不兼容，通过这样的方式解决

**Comment by arcticfox1919** [comment]
There is no point in modifying the cache, and this will not solve the problem. Please upgrade kotlin-gradle-plugin as soon as possible.

**Comment by jimmyfly100** [comment]
1.0.7版本已提升到1.6.10
