### ISSUE TITLE
flutter android平台跑不起来，能修复吗？具体错误如图：

### ISSUE THREAD

**Issue by yuanliangYL** [libpag/pag-flutter#8]
我直接跑的Demo，iOS可以启动，Android启动崩溃，请问可以处理吗？
![截屏2023-03-07 02 23 31](https://user-images.githubusercontent.com/18209116/223197858-c0b6c8ca-f7b9-447f-9031-4183fa57cfd3.png)

**Comment by lzou** [comment]
so没下载下来，网络问题

**Comment by skylerpfli** [comment]
未复现问题，打包的时候拉取异常？
