### ISSUE TITLE
安卓的编译错误

### ISSUE THREAD

**Issue by HuangYuAlbert** [libpag/pag-flutter#9]
project/android/app/src/debug/AndroidManifest.xml:13:9-36 Error:
	Attribute application@allowBackup value=(false) from AndroidManifest.xml:13:9-36
	is also present at [com.tencent.tav:libpag:3.2.7.43] AndroidManifest.xml:12:9-35 value=(true).
	Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:9:5-72:19 to override.

如果把配置文件里面的false改为true就能编译得，但是我们项目中并不需要true，我们不需要云端存储android:allowBackup，所以请问在android:allowBackup为false的情况下怎么能够正常使用呢？

**Comment by skylerpfli** [comment]
并不需要android:allowBackup设置为true，也可以正常使用呀。看有没有补充信息
